### ISSUE TITLE
Request to include an optional input for transaction start and end date

### ISSUE THREAD

**Issue by Ottoswick** [nordigen/GSheets-track-finances#1]
Can you include an optional input for transaction start and end dates?

**Comment by robbernan** [comment]
Hi @Ottoswick,

Just recently we launched a feature that lets you pass date_from, date_to parameters for /api​/v2​/accounts​/{id}​/transactions​/ endpoint that would filter transactions by date. This project was not built in mind to support all functionalities of our APIs but you are welcome to create a pull request and we will add that to the project.

**Comment by kevinvdbt** [comment]
I successfully added the date_from and date_to parameters to my script, but it's still only pulling in the last 90 days of transactions. Any reason for this? I understood from the Nordigen site that the free API would support up to 730 days of history.

**Comment by robbernan** [comment]
Hey! date_from and date_to parameters will only fetch data within the timeframe the end user (i.e. you) has consented to which by default is 90 days. 

In case you want to fetch longer history than 90 days then you need to at first create custom end user agreement and change the default max_historical_days parameter. You can find more instructions in Quickstart guide Step 3:
https://nordigen.com/en/account_information_documenation/integration/quickstart_guide/ 

Adding that as step in this project before creating requisition should be fairly simple.

Let me know if you need more assistance.

**Comment by kevinvdbt** [comment]
Aha, never noticed that in the guide. Works like a charm, thanks!
________________________________

**Comment by rmeekers** [comment]
@kevinvdbt would you mind sharing your changes? That would be really helpful. Thanks in advance!
