### ISSUE TITLE
Failure to get Script Authentication

### ISSUE THREAD

**Issue by themiguelamador** [nordigen/GSheets-track-finances#2]
Fails to get google Authentication from the account. After selecting the user account, is given the information the app is forbidden and was blocked.

**Comment by robbernan** [comment]
Hi @themiguelamador,

Did you copy the GSheets project before attempting to use the project?

**Comment by themiguelamador** [comment]
Yes, 

When listing the banks, requires first authentication, and get this error, after logging in into Google Account:

<img width="552" alt="Screenshot 2022-01-14 at 08 13 09" src="https://user-images.githubusercontent.com/2944764/149473950-0bd3a402-e521-4dbf-a7df-2503e793e3b5.png">

**Comment by robbernan** [comment]
Hey,

Follow these steps to resolve it:
https://support.google.com/chrome/a/answer/6177431#zippy=%2Cblock-or-allow-one-app
