### ISSUE TITLE
Access key problem with google sheet

### ISSUE THREAD

**Issue by ChristianMuellerLiebmann** [nordigen/GSheets-track-finances#4]
When using the access key from the response of the token/new endpoint inside the google sheet, the error 401 is triggered

**Comment by JaimyM** [comment]
I have the same issue!

**Comment by robbernan** [comment]
Hi @ChristianMuellerLiebmann and @JaimyM ,

GSheets initially was created with compatibility to Nordigen API v1 and we have updated it to be compatible with API v2.

Now you should just acquire User Secrets (ID and Key) from OB portal and place those values in Gsheets. The access token will be handled by the project itself.

**Comment by JaimyM** [comment]
Hi Robert, thanks for your reply. I found the right Gsheet where I can
input my User Secrets. However, when I try this (with country 'NL') I get a
different 401:  {"summary":"Authentication failed","detail":"Invalid token
header. Token string should not contain spaces.","status_code":401}. Any
idea what could be the problem?

**Comment by robbernan** [comment]
Hi @JaimyM,

We managed to debug it and find the bug. This should be fixed now. Let me know if the issues still persist.

**Comment by JaimyM** [comment]
It works now, thanks a lot for your help!
